name: Metadata

on:
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize]

jobs:
  title_check:
    runs-on: ubuntu-latest
    name: Validate PR Title
    permissions:
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4

      - name: Install commitlint
        run: |
          npm install --save-dev @commitlint/config-conventional@18.6.0
          npm install --save-dev @commitlint/cli@18.6.0

      - name: Lint PR title
        run: echo "${{ github.event.pull_request.title }}" | npx commitlint
